name: Dynmap Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-dynmap-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Disable automatic token usage for security

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dynmap_timemachine

    - name: Shopping District
      run: |
        dynmap-timemachine.py https://dynmap.cubekrowd.net/ survival flat [12238,64,-3625] [4,4] 1 assets2/ShoppingDistrict.png

    - name: Spawn
      run: |
        dynmap-timemachine.py https://dynmap.cubekrowd.net/ survival flat [12300,64,-3000] [4,4] 1 assets2/Spawn.png

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Action"
        git add assets2/ShoppingDistrict.png assets2/Spawn.png
        git commit -m "Update dynmap images"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
